---
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    namespace: work-default
    name: teamcity-agent1-pv
    labels:
      release: stable
      environment: production
      app: teamcity
      type: local-agent1
  spec:
    storageClassName: manual
    capacity:
      storage: 1Gi
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: "/D/Docker/Data/TeamCity/agent1"

---
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    namespace: work-default
    name: teamcity-agent2-pv
    labels:
      release: stable
      environment: production
      app: teamcity
      type: local-agent2
  spec:
    storageClassName: manual
    capacity:
      storage: 1Gi
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: "/D/Docker/Data/TeamCity/agent2"
