---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: work-default
    name: teamcity-server-service
    labels:
      release: stable
      environment: production
      app: teamcity
      type: service
  spec:
    selector:
      release: stable
      environment: production
      app: teamcity
      type: server
    ports:
    - protocol: TCP
      port: 8111
    type: NodePort
