FROM atlassian/confluence-server:6.14.2-alpine-adoptopenjdk8

RUN sed -i '/log4j.category.com.atlassian.confluence.util.AccessLogFilter=INFO/s/^#//' /opt/atlassian/confluence/confluence/WEB-INF/classes/log4j.properties

RUN sed -i '/<\/web-app>/i \    <filter-mapping>\n        <filter-name>AccessLogFilter</filter-name>\n        <url-pattern>/*</url-pattern>\n    </filter-mapping>' /opt/atlassian/confluence/confluence/WEB-INF/web.xml