FROM atlassian/confluence-server:6.14.2-alpine-adoptopenjdk8

confluence/WEB-INF/classes/log4j.properties
log4j.category.com.atlassian.confluence.util.AccessLogFilter=INFO

confluence/WEB-INF/web.xml
<filter-mapping>
   <filter-name>AccessLogFilter</filter-name>
   <url-pattern>/*</url-pattern>
</filter-mapping>