---
- name: Install utils
  apt:
    name: ['libpq-dev', 'python3-dev']
    update_cache: yes

- name: Install pip modules
  pip:
    name: ['beautifulsoup4', 'psycopg2', 'atlassian-python-api']

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "{{ scripts }}"

- name: Copy scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0777
  with_items:
    - { src: "confluence_check.sh", dest: "{{ scripts }}" }
    - { src: "postgres_check.sh", dest: "{{ scripts }}" }