---
- hosts: confluencepostgres
  become: yes
  become_method: sudo
  vars:
    postgres_password: "111111"
    postgres_user: "confluence"
    postgres_data: "/data/postgres"
    postgres_build: "/data/build_postgres"
    confluence_build: "/data/build_confluence"
    confluence_data: "/data/confluence"
    elasticsearch_data: "/data/elasticsearch"
    logstash_build: "/data/build_logstash"
    scripts: "/data/scripts"
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - docker
    - confluence-postgres
    - monitoring