---

- name: Elasticsearch | Add Elasticsearch repository key
  apt_key:
    url: "{{ es_apt_key }}"
    id: "{{ es_apt_key_id }}"
    state: present

- name: Elasticsearch | Add Elasticsearch repository
  apt_repository:
    repo: "{{ es_apt_url }}"
    state: present

- name: Elasticsearch | Install Elasticsearch
  apt:
    name: "elasticsearch={{ es_version }}"
    state: present
    update_cache: yes

- name: Elasticsearch | Enable Elasticsearch service to start on boot
  systemd:
    name: elasticsearch
    state: stopped
    enabled: yes

- name: Elasticsearch | Create Elasticsearch data directory
  file:
    path: /data/elasticsearch
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0750

- name: Elasticsearch | Copy Elasticsearch config
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0644
    force: yes
    backup: yes

- name: Elasticsearch | Modify JVM options
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  with_items:
    - { regexp: "^-Xms.*g", line: "-Xms{{ es_jvm_xms }}g" }
    - { regexp: "^-Xmx.*g", line: "-Xmx{{ es_jvm_xmx }}g" }

- name: Elasticsearch | Create Elasticsearch systemd directory
  file:
    path: /etc/systemd/system/elasticsearch.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Elasticsearch | Copy Elasticsearch systemd config
  copy:
    src: elasticsearch.conf
    dest: /etc/systemd/system/elasticsearch.service.d/elasticsearch.conf
    owner: root
    group: elasticsearch
    mode: 0644
    force: yes
    backup: no

- name: Elasticsearch | Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Elasticsearch | Copy custom limits config
  copy:
    src: 90-custom.conf
    dest: /etc/security/limits.d/90-custom.conf
    owner: root
    group: root
    mode: 0644
    force: yes
    backup: no

- name: Elasticsearch | Include security (bootstrap password)
  include: security-bootstrap-password.yml
  when: es_init_system_user and es_init_system_user is defined

- name: Elasticsearch | Start Elasticsearch service
  systemd:
    name: elasticsearch
    state: started
    enabled: yes

- name: Elasticsearch | Wait for Elasticsearch to startup
  wait_for:
    host: "{{ ansible_host }}"
    port: "{{ es_http_port }}"
    delay: 10
    connect_timeout: 5

- name: Elasticsearch | Include security (system users)
  include: security-system-users.yml
  when: es_init_system_user and es_init_system_user is defined
