{{- if .Values.imagePullSecrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  annotations:
    helm.sh/hook-weight: "-5"
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.secret }}
type: kubernetes.io/dockerconfigjson
{{- end -}}
