---
- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "/data"
    - "{{ confluence_build }}"
    - "{{ logstash_build }}"
    - "{{ postgres_data }}"
    - "{{ confluence_data }}"
    - "{{ elasticsearch_data }}"

- name: Write system parameters
  lineinfile:
    path: /etc/sysctl.conf
    line: vm.max_map_count=262144

- name: Set system parameters
  shell: sysctl -p
  args:
    executable: /bin/bash

- name: Set system users
  shell: useradd postgres -u 999 -g 999
  args:
    executable: /bin/bash

- name: Copy compose file
  template:
    src: docker-compose.yml.j2
    dest: /data/docker-compose.yml

- name: Copy build files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "Dockerfile-confluence", dest: "{{ confluence_build }}/Dockerfile" }
    - { src: "Dockerfile-logstash", dest: "{{ logstash_build }}/Dockerfile" }
    - { src: "pipeline", dest: "{{ logstash_build }}" }
    - { src: "config", dest: "{{ logstash_build }}" }

- name: Create and start containers
  docker_compose:
    project_src: /data
    pull: yes
    state: present
  register: output

- debug:
    var: output

- name: Check data directory permissions
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "{{ confluence_data }}"