---
- hosts: jenkins
  become: yes
  become_method: sudo
  vars:
    jenkins_version: 2.190
    jenkins_default_config: /etc/default/jenkins
    jenkins_work_directory: /var/lib/jenkins
    jenkins_port: 8080
  roles:
    - jenkins