apiVersion: 1

datasources:
  - name: postgres
    type: postgres
    url: $POSTGRES_HOST:5432
    database: $POSTGRES_DB
    user: $POSTGRES_USER
    isDefault: true
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1200
      timescaledb: false
