---

- name: Kibana | Create keystore
  shell: /usr/share/kibana/bin/kibana-keystore create --allow-root
  no_log: true

- name: Kibana | Set username
  shell: echo "kibana_system" | /usr/share/kibana/bin/kibana-keystore add -x -f --allow-root 'elasticsearch.username'
  no_log: true

- name: Kibana | Set password
  shell: echo {{ es_api_basic_auth_password | quote }} | /usr/share/kibana/bin/kibana-keystore add -x -f --allow-root 'elasticsearch.password'
  no_log: true
