---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: work-mongodb
  name: mongodb-server1
  labels:
    release: stable
    environment: production
    app: mongodb
    type: server1
spec:
  selector:
    matchLabels:
      release: stable
      environment: production
      app: mongodb
      type: server1
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        release: stable
        environment: production
        app: mongodb
        type: server1
    spec:
      containers:
        - name: mongodb-server1
          image: mongo:4.2.6-bionic
          args:
            - 
        env:
        - name: SERVER_URL
          value: http://teamcity-server-service:8111
        - name: AGENT_NAME
          value: build-agent1
        - name: DOCKER_IN_DOCKER
          value: start
        volumeMounts:
        - name: teamcity-agent1-pvc
          mountPath: /data/teamcity_agent/conf
        securityContext:
          privileged: true
      restartPolicy: Always
      volumes:
      - name: teamcity-agent1-pvc
        persistentVolumeClaim:
          claimName: teamcity-agent1-pvc

---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: work-teamcity
    name: teamcity-agent2
    labels:
      release: stable
      environment: production
      app: teamcity
      type: agent2
  spec:
    selector:
      matchLabels:
        release: stable
        environment: production
        app: teamcity
        type: agent2
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          release: stable
          environment: production
          app: teamcity
          type: agent2
      spec:
        containers:
        - name: teamcity-agent2
          image: jetbrains/teamcity-agent:2019.2.2-linux
          env:
          - name: SERVER_URL
            value: http://teamcity-server-service:8111
          - name: AGENT_NAME
            value: build-agent2
          - name: DOCKER_IN_DOCKER
            value: start
          volumeMounts:
          - name: teamcity-agent2-pvc
            mountPath: /data/teamcity_agent/conf
          securityContext:
            privileged: true
        restartPolicy: Always
        volumes:
        - name: teamcity-agent2-pvc
          persistentVolumeClaim:
            claimName: teamcity-agent2-pvc





---

                      args:
                      - mongod
                      - --wiredTigerCacheSizeGB
                      - "3"
                      volumeMounts:
                      - mountPath: /data/db
                        name: prod-form-one-mongo-persistent-volume-claim
                    restartPolicy: Always
                    volumes:
                    - name: prod-form-one-mongo-persistent-volume-claim
                      persistentVolumeClaim:
                        claimName: prod-form-one-mongo-persistent-volume-claim




                      volumeMounts:
                        - name: mongo-key
                          mountPath: "/etc/secrets-volume"
                          readOnly: true

                      volumes:
                        - name: mongo-key
                          secret:
                            defaultMode: 0400
                            secretName: mongo-key