---

apiVersion: v1
kind: Service
metadata:
  namespace: work-mongodb
  name: mongodb-server1-service
  labels:
    release: stable
    environment: production
    app: mongodb
    type: service-server1
spec:
  selector:
    release: stable
    environment: production
    app: mongodb
    type: server1
  ports:
    - protocol: TCP
      port: 27017
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  namespace: work-mongodb
  name: mongodb-server2-service
  labels:
    release: stable
    environment: production
    app: mongodb
    type: service-server2
spec:
  selector:
    release: stable
    environment: production
    app: mongodb
    type: server2
  ports:
    - protocol: TCP
      port: 27017
  type: NodePort
