---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: work-mongodb
  name: mongodb-server1-pvc
  labels:
    release: stable
    environment: production
    app: mongodb
    type: claim-server1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      release: stable
      environment: production
      app: mongodb
      type: local-server1

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: work-mongodb
  name: mongodb-server2-pvc
  labels:
    release: stable
    environment: production
    app: mongodb
    type: claim-server2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      release: stable
      environment: production
      app: mongodb
      type: local-server2
