---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: work-mongodb
  name: mongodb-server1
  labels:
    release: stable
    environment: production
    app: mongodb
    type: server1
spec:
  selector:
    matchLabels:
      release: stable
      environment: production
      app: mongodb
      type: server1
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        release: stable
        environment: production
        app: mongodb
        type: server1
    spec:
      containers:
        - name: mongodb-server1
          image: mongo:4.2.6-bionic
          args:
            # - --keyFile
            # - /etc/secret-key/mongodb-server.key
            # - --auth
            - --wiredTigerCacheSizeGB
            - "1.5"
            - --replSet
            - rs0
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
          volumeMounts:
            # - name: mongodb-server1-pvc
            #   mountPath: /data/db
            - name: mongodb-backup1-pvc
              mountPath: /backup
            # - name: mongodb-key-pvc
            #   mountPath: /etc/secret-key
            #   readOnly: true
      restartPolicy: Always
      volumes:
        # - name: mongodb-server1-pvc
        #   persistentVolumeClaim:
        #     claimName: mongodb-server1-pvc
        - name: mongodb-backup1-pvc
          persistentVolumeClaim:
            claimName: mongodb-backup1-pvc
        # - name: mongodb-key-pvc
        #   persistentVolumeClaim:
        #     claimName: mongodb-key-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: work-mongodb
  name: mongodb-server2
  labels:
    release: stable
    environment: production
    app: mongodb
    type: server2
spec:
  selector:
    matchLabels:
      release: stable
      environment: production
      app: mongodb
      type: server2
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        release: stable
        environment: production
        app: mongodb
        type: server2
    spec:
      containers:
        - name: mongodb-server2
          image: mongo:4.2.6-bionic
          args:
            # - --keyFile
            # - /etc/secret-key/mongodb-server.key
            # - --auth
            - --wiredTigerCacheSizeGB
            - "1.5"
            - --replSet
            - rs0
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
          volumeMounts:
            # - name: mongodb-server2-pvc
            #   mountPath: /data/db
            - name: mongodb-backup2-pvc
              mountPath: /backup
            # - name: mongodb-key-pvc
            #   mountPath: /etc/secret-key
            #   readOnly: true
      restartPolicy: Always
      volumes:
        # - name: mongodb-server2-pvc
        #   persistentVolumeClaim:
        #     claimName: mongodb-server2-pvc
        - name: mongodb-backup2-pvc
          persistentVolumeClaim:
            claimName: mongodb-backup2-pvc
        # - name: mongodb-key-pvc
        #   persistentVolumeClaim:
        #     claimName: mongodb-key-pvc
