---

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: work-mongodb
  name: mongodb-server1-pv
  labels:
    release: stable
    environment: production
    app: mongodb
    type: local-server1
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/D/Docker/Data/MongoDB/server1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: work-mongodb
  name: mongodb-server2-pv
  labels:
    release: stable
    environment: production
    app: mongodb
    type: local-server2
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/D/Docker/Data/MongoDB/server2"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: work-mongodb
  name: mongodb-backup1-pv
  labels:
    release: stable
    environment: production
    app: mongodb
    type: local-backup1
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/D/Docker/Data/MongoDB/backup1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: work-mongodb
  name: mongodb-backup2-pv
  labels:
    release: stable
    environment: production
    app: mongodb
    type: local-backup2
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/D/Docker/Data/MongoDB/backup2"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: work-mongodb
  name: mongodb-key-pv
  labels:
    release: stable
    environment: production
    app: mongodb
    type: local-key
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/D/Docker/Data/MongoDB/key"
