---
- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"

- name: Install docker and etc
  apt:
    name: ['docker-ce=17.06.2~ce-0~ubuntu', 'docker-compose=1.17.0', 'python3-pip']
    update_cache: yes

- name: Install docker modules
  pip:
    name: "{{ item }}"
  with_items:
    - docker
    - docker-compose